package:
  name: sample-fastapi
  version: 0.1.0
  description: sample fastapi app
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  dependencies:
    runtime:
      - python3
    provides:
      - so:ld-linux-x86-64.so.2
      - so:libc.so.6
      - so:libexpat.so.1
      - so:libm.so.6
environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - ca-certificates-bundle
      - busybox
      - py3-pip
      - py3-virtualenv
pipeline:
  - name: Build Python application
    runs: |
      WEBAPPDIR="${{targets.destdir}}/opt/sample-fastapi/"
      mkdir -p "${WEBAPPDIR}"
      cp -r app/ "${WEBAPPDIR}/app"
      virtualenv "${WEBAPPDIR}/venv"
      sh -c "source '${WEBAPPDIR}/venv/bin/activate' && pip install -r requirements.txt"
